spring:
  application:
    name: create-customer-in-square
  cloud:
    function:
      definition: createCustomerInSquare
create-customer-in-square:
  square:
    access-token: ${SQUARE_ACCESS_KEY}
    environment: sandbox
---
spring:
  config:
    activate:
      on-profile: prod
create-customer-in-square:
  square:
    environment: production
