spring:
  application:
    name: send-email-alert
  cloud:
    function:
      definition: sendEmailAlert
send-email-alert:
  email:
    sender: Gareth Yoder <gyoder@cedarmeadowmeats.com>
    no-reply-sender: noReply <noReply@cedarmeadowmeats.com>
    admin-emails: >
      Gareth Yoder <gyoder@cedarmeadowmeats.com>,
      Joy Yoder <jyoder@cedarmeadowmeats.com>
    defaultAlertEmail: templates/email/alertEmail/defaultAlertEmail.html
    orderFormAlertEmail: templates/email/alertEmail/orderFormAlertEmail.html
  dj-email:
    sender: Gareth Yoder <gyoder@gyoderaudioexpressions.com>
    no-reply-sender: noReply <noReply@gyoderaudioexpressions.com>
    admin-emails: Gareth Yoder <garethyoder@yahoo.com>
    defaultAlertEmail: templates/email/alertEmail/djFormAlertEmail.html
---
spring:
  config:
    activate:
      on-profile: tc
send-email-alert:
  email:
    defaultAlertEmail: src/main/resources/templates/email/alertEmail/defaultAlertEmail.html
    orderFormAlertEmail: src/main/resources/templates/email/alertEmail/orderFormAlertEmail.html
  dj-email:
    defaultAlertEmail: src/main/resources/templates/email/alertEmail/djFormAlertEmail.html
---
spring:
  config:
    activate:
      on-profile: local
  main:
    web-application-type: servlet
send-email-alert:
  email:
    defaultAlertEmail: src/main/resources/templates/email/alertEmail/defaultAlertEmail.html
    orderFormAlertEmail: src/main/resources/templates/email/alertEmail/orderFormAlertEmail.html
  dj-email:
    defaultAlertEmail: src/main/resources/templates/email/alertEmail/djFormAlertEmail.html